### ISSUE TITLE
Empty category page

### ISSUE THREAD

**Issue by qbart** [Selleo/til#111]
When opening empty category like this one:  https://til.selleo.com/category/erlang we see empty space, should we add some icon/text for empty state?

**Comment by qbart** [comment]
@michalgren what do you think?

**Comment by ZajoncM** [comment]
I solved this issue in https://github.com/Selleo/til/pull/131

![image](https://user-images.githubusercontent.com/52612822/149525890-f4ca7461-ca96-4a98-bdde-8206d99ab9b8.png)
