### ISSUE TITLE
Inline code should be similar to the block of code

### ISSUE THREAD

**Issue by qbart** [Selleo/til#124]
Have a look a this post:
https://til.selleo.com/posts/421-hash-content-of-a-binary-file
You can barely see the inline code compare to the block of code like here:
https://til.selleo.com/posts/718-use-env-variable-in-jq-as-json-key

**Comment by qbart** [comment]
@michalgren should we make them the same?

**Comment by michalgren** [comment]
![code:inlinecode](https://user-images.githubusercontent.com/36044370/148774966-ff1daade-a3ea-42bd-940f-edcd690707ef.png)
