### ISSUE TITLE
No posts or categories

### ISSUE THREAD

**Issue by qbart** [Selleo/til#149]
Visiting root page as an anonymous user does not return categories and posts on Chrome sometimes, it says: not found.
Opening page on fresh Firefox works. Signing in to Chrome and signing out fixes the issue but this should not happen.

Need to investigate, maybe some state leftovers? invalid user session after some time of inactivity?

**Comment by typeWolffo** [comment]
@qbart I was not able to reproduce this bug, is it possible that bug was fixed In this [PR](https://github.com/Selleo/til/pull/150)

**Comment by qbart** [comment]
ok, I will check it out on Monday again

**Comment by qbart** [comment]
can't reproduce
