### ISSUE TITLE
Avatars are missing

### ISSUE THREAD

**Issue by qbart** [Selleo/til#92]
Frontend: should use generic image when image is empty

**Comment by michalgren** [comment]
Generic avatar: https://xd.adobe.com/view/2547df18-c699-40c1-9e26-0651a835b38a-7014/screen/37a37d31-1099-4071-8233-636a8e7951f7/

**Comment by qbart** [comment]
Frontend: should use generic image when image is null
Backend: after login should update user with avatar img
