### ISSUE TITLE
3. Pagination

### ISSUE THREAD

**Issue by qbart** [Selleo/til#93]
We need to paginate posts on the root view (all posts), category view, author view.

In the first scope we only need to have pagination for root view (currently it loads all records from database)

we need to discuss how we params are sent between client<=>server (preferred: `url?page=2`)

needs design how paginatiion will look like (we are doing classic pagination with "prev, 1, 2, ..., next" links)

**Comment by michalgren** [comment]
Here is the pagination design: https://xd.adobe.com/view/2547df18-c699-40c1-9e26-0651a835b38a-7014/screen/dad9b282-4928-4450-8519-e2b0e84f49db/
Other pagination states: https://xd.adobe.com/view/2547df18-c699-40c1-9e26-0651a835b38a-7014/screen/847b7820-782a-425a-89d2-9ee134f12f28/

**Comment by ZajoncM** [comment]
Need to change page size to 10 posts on backend
